spring:
  datasource:
    url: jdbc:mysql://localhost:3306/task_manager
    username: root
    password: Nikhil@2001
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  jpa.properties:
    hibernate:
      format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: nikhilhallikeri7@gmail.com
    password: glna mkpj kdxn yknl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
